### PR TITLE
Do not try to kill child process if it doesnt exist

### PR DESCRIPTION
**Pull request by Ricardonacif**
There are times where a process didn't initialized the cycleTLS instance, so it can't try to kill the child process. Btw thanks for the package, really helpful!

### CODE REVIEW

**Comment by Ricardonacif** [comment]
Also, sometimes I see the cycleTLS go process up even after the node process is down. Would there be a way for the go process to kill itself if the parent process is dead? I'm not too familiar with go but if you think it's a valid feature I could try to implement it.

**Comment by Danny-Dasilva** [comment]
The CycleTLS server instance has been moved to the Golang side as of [this PR](https://github.com/Danny-Dasilva/CycleTLS/pull/74). This means the package can be imported from JS multiple times and connect to the same server. 

I can add in a timeout on the Go side, where if no new websocket messages are received (coming from js/ts) for some specified amount of time the process ends. Let me know if there are any other issues with this change and I'll include them in.

**Comment by Danny-Dasilva** [comment]
Along with this we can also have the WebSocket instance be able to send a kill command to the server.

**Comment by Ricardonacif** [comment]
Awesome!

**Pull request closed without merging**
